name: azureml-lora-finetune
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.9.1
      - transformers==4.57.3
      - peft==0.18.0
      - bitsandbytes==0.45.0
      - accelerate==1.12.0
      - datasets==4.4.1
      - pyyaml==6.0.3
      - python-dotenv==1.2.1
      - azure-storage-blob==12.19.0
